//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RLogin.rc
//
#define IDC_RESET                       3
#define IDR_MAINFRAME                   100
#define IDR_RLOGINTYPE                  101
#define IDR_SFTPMENU                    102
#define IDE_MESSAGE_ANYPASTE            102
#define IDR_SFTPTOOL                    103
#define IDE_PASSWORDNOMATCH             103
#define IDI_ACTIVE                      104
#define IDE_MAKEIDKEY                   104
#define IDP_SOCKETS_INIT_FAILED         105
#define IDS_INDICATOR_STAT              106
#define IDE_DELETEKEYQES                106
#define IDB_BITMAP1                     107
#define IDE_USEPASSWORDIDKEY            107
#define IDB_BITMAP2                     108
#define IDE_IDKEYLOADERROR              108
#define IDB_BITMAP3                     109
#define IDE_DUPIDKEYENTRY               109
#define IDB_BITMAP4                     110
#define IDE_IDKEYPASSERROR              110
#define IDB_BITMAP5                     111
#define IDE_IDKEYSAVEERROR              111
#define IDB_BITMAP6                     112
#define IDE_IDKEYCREATEERROR            112
#define IDB_BITMAP7                     113
#define IDE_HISTORYBACKUPERROR          113
#define IDD_ABOUTBOX                    114
#define IDE_LOGOPENERROR                114
#define IDD_ALGOPARADLG                 115
#define IDE_PORTFWORDERROR              115
#define IDD_CHARSETPAGE                 116
#define IDE_SSHGLOBALREQERROR           116
#define IDD_CHMODDLG                    117
#define IDE_ALLCLOSEREQ                 117
#define IDD_COLORPARADLG                118
#define IDS_IDKEYFILELOAD               118
#define IDD_EDITDLG                     119
#define IDS_IDKEYFILESAVE               119
#define IDD_FONTPARADLG                 120
#define IDS_IDKEYCREATE                 120
#define IDD_ICONVDLG                    121
#define IDS_IDKEYRENAME                 121
#define IDD_IDKEYDLG                    122
#define IDS_IDKEYFILELOADCOM            122
#define IDD_IDKEYFILEDLG                123
#define IDS_IDKEYFILESAVECOM            123
#define IDD_IDKEYPARADLG                124
#define IDS_IDKEYCREATECOM              124
#define IDD_KEYLISTPAGE                 125
#define IDE_INFOCAPCONVERROR            125
#define IDD_KEYPARADLG                  126
#define IDE_INFOCAPOVER1024             126
#define IDD_PASSDLG                     127
#define IDE_INFOCAPINFOCONVERROR        127
#define IDD_PFDLISTDLG                  128
#define IDS_INITBUTTON                  128
#define IDD_PFDPARADLG                  129
#define IDS_ALLINITREQ                  129
#define IDD_PROGDLG                     130
#define IDE_UPDATERESUMEERROR           130
#define IDD_PROTOPAGE                   131
#define IDS_FILEDLGIMAGE                131
#define IDD_SERENTDLG                   132
#define IDS_FILEDLGGRAPHICS             132
#define IDD_SERVERLIST                  133
#define IDS_FILEDLGHISTORY              133
#define IDD_SFTPDLG                     134
#define IDS_FILEDLGLOGFILE              134
#define IDD_SSHALGO                     135
#define IDS_FILEDLGALLFILE              135
#define IDD_TERMPAGE                    136
#define IDS_FILEDLGRLOGIN               136
#define IDD_UPDATEDLG                   137
#define IDS_FILEDLGTEKIMAGE             137
#define IDD_IDKEYSELDLG                 138
#define IDS_FILEDLGTEKIMAGE2            138
#define IDS_IDKEYFILEDELREQ             139
#define IDR_POPUPMENU                   140
#define IDS_SERVERENTRYDELETE           140
#define IDD_ENTRYPAGE                   141
#define IDD_SERENTPAGE                  141
#define IDR_TEKWND                      141
#define IDE_PROTOCOLENTRY               141
#define IDR_GRAPWND                     142
#define IDE_USESERVERENTRY              142
#define IDS_PROTODLGTITLE               143
#define IDS_PRORODLGCOMM                144
#define IDS_CERTTRASTREQ                145
#define IDD_CHATDLG                     146
#define IDS_STRING146                   146
#define IDS_IDKEYDUPHOSTNAME            146
#define IDD_CHATSTAT                    147
#define IDE_FILENAMEERROR               147
#define IDS_LOCALFILEDELETE             148
#define IDD_PROXYDLG                    149
#define IDS_REMOTEFILEDELETE            149
#define IDD_SCRNPAGE                    150
#define IDS_FILEDELETEREQ               150
#define IDS_FILECOUNTMSG                151
#define IDD_AUTORENDLG                  152
#define IDE_KANJICONVERROR              152
#define IDS_CREATEDIRMSG                153
#define IDD_INFOCAPDLG                  154
#define IDS_STRING154                   154
#define IDS_RENAMEMSG                   154
#define IDD_ENVDLG                      155
#define IDE_MANYCHANNEL                 155
#define IDD_ESCDLG                      156
#define IDD_ESCPARADLG                  157
#define IDD_CSIPARADLG                  158
#define IDD_STATUS_DLG                  160
#define IDD_GHOSTWND                    161
#define IDD_HISPAGE                     161
#define IDD_SEARCHDLG                   162
#define IDD_CERTKEYDLG                  163
#define IDD_CLIPBOARDPAGE               164
#define IDD_MOUSEPAGE                   165
#define IDD_INITALLDLG                  167
#define IDD_DIALOG1                     168
#define IDD_SCRIPTDLG                   168
#define IDM_KANJI_EUC                   200
#define IDM_KANJI_SJIS                  201
#define IDM_KANJI_ASCII                 202
#define IDM_KANJI_UTF8                  203
#define IDM_SFTP                        204
#define IDM_SFTP_ABORT                  205
#define IDM_SFTP_ALLDOWNLOAD            206
#define IDM_SFTP_ALLUPLOAD              207
#define IDM_SFTP_CHMOD                  208
#define IDM_SFTP_CLOSE                  209
#define IDM_SFTP_DELETE                 210
#define IDM_SFTP_DOWNLOAD               211
#define IDM_SFTP_MKDIR                  212
#define IDM_SFTP_REFLESH                213
#define IDM_SFTP_RENAME                 214
#define IDM_SFTP_UPLOAD                 215
#define IDM_XMODEM_UPLOAD               216
#define IDM_YMODEM_UPLOAD               217
#define IDM_ZMODEM_UPLOAD               218
#define IDM_XMODEM_DOWNLOAD             219
#define IDM_YMODEM_DOWNLOAD             220
#define IDM_ZMODEM_DOWNLOAD             221
#define IDM_KERMIT_UPLOAD               222
#define IDM_KERMIT_DOWNLOAD             223
#define IDM_RESET_TAB                   224
#define IDM_RESET_BANK                  225
#define IDM_RESET_ATTR                  226
#define IDM_RESET_TEK                   227
#define IDM_RESET_ESC                   228
#define IDM_RESET_MOUSE                 229
#define IDM_RESET_ALL                   230
#define IDM_CHATSTOP                    231
#define IDM_TEKDISP                     232
#define IDM_TEK_CLOSE                   233
#define IDM_TEK_SAVE                    234
#define IDM_TEK_CLEAR                   235
#define IDM_TEK_MODE                    236
#define IDM_CAP_INPORT                  237
#define IDM_CAP_EXPORT                  238
#define IDM_CAPL_CLIP                   239
#define IDM_CAPL_CLIPBORD               240
#define IDM_CAP_CLIPBORD                241
#define IDM_INFO_INPORT                 242
#define IDM_INFO_EXPORT                 243
#define IDM_INFO_CLIPBORD               244
#define IDM_BROADCAST                   245
#define IDM_SERV_INPORT                 246
#define IDM_SERV_EXPORT                 247
#define IDM_SOCKETSTATUS                248
#define IDC_BACKFILE                    1000
#define IDC_BACKSEL                     1001
#define IDC_BANKGL1                     1002
#define IDC_BANKGL2                     1003
#define IDC_BANKGL3                     1004
#define IDC_BANKGL4                     1005
#define IDC_BANKGR1                     1006
#define IDC_BANKGR2                     1007
#define IDC_BANKGR3                     1008
#define IDC_BANKGR4                     1009
#define IDC_BOXBACK                     1010
#define IDC_BOXTEXT                     1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON3                     1014
#define IDC_BUTTON5                     1015
#define IDC_REMOTE_UP                   1015
#define IDC_CHARBANK                    1016
#define IDC_CHARBANK1                   1017
#define IDC_CHARBANK2                   1018
#define IDC_CHARBANK3                   1019
#define IDC_CHARBANK4                   1020
#define IDC_CHARSET                     1021
#define IDC_CHARSET1                    1022
#define IDC_CHARSET2                    1023
#define IDC_CHARSET3                    1024
#define IDC_CHARSET4                    1025
#define IDC_CHMOD1                      1026
#define IDC_CHMOD2                      1027
#define IDC_CHMOD3                      1028
#define IDC_CHMOD4                      1029
#define IDC_CHMOD5                      1030
#define IDC_CHMOD6                      1031
#define IDC_CHMOD7                      1032
#define IDC_CHMOD8                      1033
#define IDC_CHMOD9                      1034
#define IDC_COLSET                      1035
#define IDC_COMCONFIG                   1036
#define IDC_CONNECTHOST                 1037
#define IDC_CONNECTPORT                 1038
#define IDC_DELAYMSEC                   1039
#define IDC_DELENTRY                    1040
#define IDC_DISPOFFSET                  1041
#define IDC_DISPZOOM                    1042
#define IDC_DSA2COPY                    1043
#define IDC_DISPZOOM2                   1043
#define IDC_DSA2MAKE                    1044
#define IDC_FONTQUALITY                 1044
#define IDC_DSA2PUB                     1045
#define IDC_EDIT1                       1046
#define IDC_EDITENTRY                   1047
#define IDC_EDIT3                       1047
#define IDC_ENDTIME                     1048
#define IDC_EDIT4                       1048
#define IDC_ENTRYNAME                   1049
#define IDC_FACENAME                    1050
#define IDC_ENTRYMEMO                   1050
#define IDC_FILENAME                    1051
#define IDC_FONTCODE                    1052
#define IDC_FILENAME2                   1052
#define IDC_FONTLIST                    1053
#define IDC_FONTLISTDEL                 1054
#define IDC_FONTLISTEDIT                1055
#define IDC_FONTLISTNEW                 1056
#define IDC_FONTSEL                     1057
#define IDC_HISMAX                      1058
#define IDC_ICONVSET                    1059
#define IDC_IDKEYFILE                   1060
#define IDC_IDKEYLOAD                   1061
#define IDC_IDKEYSAVE                   1062
#define IDC_IDKEYSEL                    1063
#define IDC_KANJICODE1                  1064
#define IDC_KANJICODE2                  1065
#define IDC_KANJICODE3                  1066
#define IDC_KANJICODE4                  1067
#define IDC_KEYASNDEL                   1068
#define IDC_KEYASNEDIT                  1069
#define IDC_KEYASNNEW                   1070
#define IDC_KEYCODE                     1071
#define IDC_KEYASNMETA                  1071
#define IDC_KEYFILENAME                 1072
#define IDC_KEYFILESELECT               1073
#define IDC_KEYLIST                     1074
#define IDC_KEYMAPS                     1075
#define IDC_KEYSTAT1                    1076
#define IDC_KEYSTAT2                    1077
#define IDC_KEYSTAT3                    1078
#define IDC_LISTENHOST                  1079
#define IDC_KEYSTAT4                    1079
#define IDC_LISTENPORT                  1080
#define IDC_KEYSTAT5                    1080
#define IDC_LOADDEFAULT                 1081
#define IDC_KEYSTAT6                    1081
#define IDC_LOCAL_CWD                   1082
#define IDC_LOCAL_LIST                  1083
#define IDC_LOGINNAME                   1084
#define IDC_KEYSTAT9                    1084
#define IDC_MDI_TAB_CTRL                1085
#define IDC_MDI_TAB_CTRL_BAR            1086
#define IDC_NEWENTRY                    1087
#define IDC_OPTION                      1088
#define IDC_PASSNAME                    1089
#define IDC_PASSWORD                    1090
#define IDC_PASSNAME2                   1090
#define IDC_PFDDEL                      1091
#define IDC_PFDEDIT                     1092
#define IDC_PFDLIST                     1093
#define IDC_PFDNEW                      1094
#define IDC_PROGRESS1                   1095
#define IDC_PROMPT                      1096
#define IDC_RADIO1                      1097
#define IDC_RADIO2                      1098
#define IDC_RADIO3                      1099
#define IDC_RADIO4                      1100
#define IDC_RADIO5                      1101
#define IDC_REMOTE_CWD                  1102
#define IDC_REMOTE_LIST                 1103
#define IDC_RSA1COPY                    1104
#define IDC_RSA1MAKE                    1105
#define IDC_RSA1PUB                     1106
#define IDC_RSA2COPY                    1107
#define IDC_RSA2MAKE                    1108
#define IDC_RSA2PUB                     1109
#define IDC_SAVEDEFAULT                 1110
#define IDC_SCRNSIZE1                   1111
#define IDC_SCRNSIZE2                   1112
#define IDC_SCSZCOLS                    1113
#define IDC_SCSZFONT                    1114
#define IDC_SERVERLIST                  1115
#define IDC_SCSZCOLS2                   1115
#define IDC_SERVERNAME                  1116
#define IDC_SCSZFONT2                   1116
#define IDC_FONTHW                      1116
#define IDC_SHIFT                       1117
#define IDC_SIZEPROG                    1118
#define IDC_SOCKNO                      1119
#define IDC_SSHALGO                     1120
#define IDC_SOCKNO2                     1120
#define IDC_GROUP                       1120
#define IDC_SSHIDKEY                    1121
#define IDC_SSHPFD                      1122
#define IDC_TERMNAME                    1123
#define IDC_TIMELIMIT                   1124
#define IDC_TITLE                       1125
#define IDC_TOTALSIZE                   1126
#define IDC_TRANSPARENT                 1127
#define IDC_TRANSRATE                   1128
#define IDC_USERNAME                    1129
#define IDC_WHEELSIZE                   1130
#define IDC_USERNAME2                   1130
#define IDC_HOSTADDR                    1130
#define IDC_VISUALBELL                  1131
#define IDC_VISUALBELL2                 1132
#define IDC_RECVCRLF                    1132
#define IDC_MOUSE_BTN1                  1133
#define IDC_HISFILE_SEL                 1134
#define IDC_AUTOLOG_SEL                 1135
#define IDC_MOUSE_BTN2                  1135
#define IDC_COMBO1                      1136
#define IDC_IDKEY_TYPE                  1136
#define IDC_ECHOCRLF                    1136
#define IDC_SENDCRLF                    1136
#define IDC_COMBO2                      1137
#define IDC_IDKEY_BITS                  1137
#define IDC_MOUSE_KEY1                  1137
#define IDC_LIST2                       1138
#define IDC_IDKEY_LIST                  1138
#define IDC_MOUSE_KEY2                  1138
#define IDC_ESCEDIT                     1138
#define IDC_BUTTON4                     1139
#define IDC_IDKEY_UP                    1139
#define IDC_COMBO3                      1139
#define IDC_BUTTON6                     1140
#define IDC_IDKEY_DOWN                  1140
#define IDC_IDKEY_DEL                   1141
#define IDC_IDKEY_INPORT                1142
#define IDC_IDKEY_EXPORT                1143
#define IDC_IDKEY_NAME                  1144
#define IDC_IDKEY_CREATE                1145
#define IDC_IDKEY_COPY                  1146
#define IDC_NAME                        1146
#define IDC_IDKEY_PROG                  1147
#define IDC_MESSAGE                     1148
#define IDC_LOCAL_UP                    1149
#define IDC_KEEPALIVE                   1153
#define IDC_CHECK1                      1157
#define IDC_CHECK2                      1158
#define IDC_SLEEPSEC                    1158
#define IDC_NODETREE                    1159
#define IDC_SENDSTR                     1160
#define IDC_RECVSTR                     1161
#define IDC_NEWNODE                     1162
#define IDC_UPDATENODE                  1163
#define IDC_DELNODE                     1164
#define IDC_NEXTNODE                    1165
#define IDC_CHATEDIT                    1165
#define IDC_MAKECHAT                    1166
#define IDC_PROXYSET                    1166
#define IDC_TIMEPROG                    1167
#define IDC_STATUS                      1168
#define IDC_EDIT2                       1170
#define IDC_TEXT                        1170
#define IDC_NAMEOK                      1174
#define IDC_ALL_SET                     1175
#define IDC_ALL_CLR                     1176
#define IDC_TEXTCOL                     1177
#define IDC_BACKCOL                     1178
#define IDC_FONTNUM                     1178
#define IDC_LIST1                       1179
#define IDC_INFOLIST                    1179
#define IDC_ENV_LIST                    1179
#define IDC_ESCLIST                     1179
#define IDC_LOADCAP                     1180
#define IDC_CSILIST                     1180
#define IDC_ENTRY                       1181
#define IDC_DCSLIST                     1181
#define IDC_LOADINFO                    1182
#define IDC_TERMCAP                     1182
#define IDC_INFOCAP                     1183
#define IDC_SSL_RADIO1                  1184
#define IDC_SSL_RADIO2                  1185
#define IDC_CODE                        1185
#define IDC_SSL_RADIO3                  1186
#define IDC_CEXT2                       1186
#define IDC_SSL_RADIO4                  1187
#define IDC_CEXT1                       1188
#define IDC_DOINIT                      1189
#define IDC_ATTR1                       1201
#define IDC_ATTR2                       1202
#define IDC_ATTR3                       1203
#define IDC_ATTR4                       1204
#define IDC_ATTR5                       1205
#define IDC_ATTR6                       1206
#define IDC_ATTR7                       1207
#define IDC_ATTR8                       1208
#define IDB_ATTR1                       1221
#define IDB_ATTR2                       1222
#define IDB_ATTR3                       1223
#define IDB_ATTR4                       1224
#define IDB_ATTR5                       1225
#define IDB_ATTR6                       1226
#define IDB_ATTR7                       1227
#define IDB_ATTR8                       1228
#define IDC_ALGO_LIST1                  2001
#define IDC_ALGO_LIST2                  2002
#define IDC_ALGO_LIST3                  2003
#define IDC_ALGO_LIST4                  2004
#define IDC_ALGO_LIST5                  2005
#define IDC_ALGO_LIST6                  2006
#define IDC_ALGO_LIST7                  2007
#define IDC_ALGO_LIST8                  2008
#define IDC_ALGO_LIST9                  2009
#define IDC_ALGO_LIST10                 2010
#define IDC_ALGO_LIST11                 2011
#define IDC_ALGO_LIST12                 2012
#define IDC_BOX0                        2100
#define IDC_BOX1                        2101
#define IDC_BOX2                        2102
#define IDC_BOX3                        2103
#define IDC_BOX4                        2104
#define IDC_BOX5                        2105
#define IDC_BOX6                        2106
#define IDC_BOX7                        2107
#define IDC_BOX8                        2108
#define IDC_BOX9                        2109
#define IDC_BOX10                       2110
#define IDC_BOX11                       2111
#define IDC_BOX12                       2112
#define IDC_BOX13                       2113
#define IDC_BOX14                       2114
#define IDC_BOX15                       2115
#define IDC_PROTO1                      2201
#define IDC_PROTO2                      2202
#define IDC_PROTO3                      2203
#define IDC_PROTO4                      2204
#define IDC_PROTO5                      2205
#define IDC_PROTO6                      2206
#define IDC_PROTOCHECK1                 2301
#define IDC_PROTOCHECK2                 2302
#define IDC_PROTOCHECK3                 2303
#define IDC_PROTOCHECK4                 2304
#define IDC_PROTOCHECK5                 2305
#define IDC_PROTOCHECK6                 2306
#define IDC_PROTOCHECK7                 2307
#define IDC_PROTOCHECK8                 2308
#define IDC_PROTOCHECK9                 2309
#define IDC_PROTOCHECK10                2310
#define IDC_PROTOCHECK11                2311
#define IDC_PROTOCHECK12                2312
#define IDC_PROTOCHECK13                2313
#define IDC_STATUS1                     2401
#define IDC_STATUS2                     2402
#define IDC_STATUS3                     2403
#define IDC_STATUS4                     2404
#define IDC_TERMCHECK1                  2501
#define IDC_TERMCHECK2                  2502
#define IDC_TERMCHECK3                  2503
#define IDC_TERMCHECK4                  2504
#define IDC_TERMCHECK5                  2505
#define IDC_TERMCHECK6                  2506
#define IDC_TERMCHECK7                  2507
#define IDC_TERMCHECK8                  2508
#define IDC_TERMCHECK9                  2509
#define IDC_METAKEY1                    3001
#define IDC_METAKEY2                    3002
#define IDC_METAKEY3                    3003
#define IDC_METAKEY4                    3004
#define IDC_METAKEY5                    3005
#define IDC_METAKEY6                    3006
#define IDC_METAKEY7                    3007
#define IDC_METAKEY8                    3008
#define IDC_METAKEY9                    3009
#define IDC_METAKEY10                   3010
#define IDC_METAKEY11                   3011
#define IDC_METAKEY12                   3012
#define IDC_METAKEY13                   3013
#define IDC_METAKEY14                   3014
#define IDC_METAKEY15                   3015
#define IDC_METAKEY16                   3016
#define IDC_METAKEY17                   3017
#define IDC_METAKEY18                   3018
#define IDC_METAKEY19                   3019
#define IDC_METAKEY20                   3020
#define IDC_METAKEY21                   3021
#define IDC_METAKEY22                   3022
#define IDC_METAKEY23                   3023
#define IDC_METAKEY24                   3024
#define IDC_METAKEY25                   3025
#define IDC_METAKEY26                   3026
#define IDC_METAKEY27                   3027
#define IDC_METAKEY28                   3028
#define IDC_METAKEY29                   3029
#define IDC_METAKEY30                   3030
#define IDC_METAKEY31                   3031
#define IDC_METAKEY32                   3032
#define IDC_METAKEY33                   3033
#define IDC_METAKEY34                   3034
#define IDC_METAKEY35                   3035
#define IDC_METAKEY36                   3036
#define IDC_METAKEY37                   3037
#define IDC_METAKEY38                   3038
#define IDC_METAKEY39                   3039
#define IDC_METAKEY40                   3040
#define IDC_METAKEY41                   3041
#define IDC_METAKEY42                   3042
#define IDC_METAKEY43                   3043
#define IDC_METAKEY44                   3044
#define IDC_METAKEY45                   3045
#define IDC_METAKEY46                   3046
#define IDC_METAKEY47                   3047
#define IDC_METAKEY48                   3048
#define IDC_METAKEY49                   3049
#define IDC_METAKEY50                   3050
#define IDC_METAKEY51                   3051
#define IDC_METAKEY52                   3052
#define IDC_TAB1                        3053
#define IDC_SERVERTAB                   3053
#define IDC_DIGEST                      3054
#define IDC_SAVEKEY                     3055
#define IDC_HOSTNAME                    3056
#define IDC_BACK                        3058
#define IDC_AUTOLOG_PATH                3058
#define IDC_HISFILE_PATH                3059
#define IDC_MSGICON                     3060
#define ID_FILE_ALL_LOAD                5000
#define ID_EDIT_BOX                     5001
#define ID_PAGE_PRIOR                   5002
#define ID_PAGE_NEXT                    5003
#define ID_APP_QUIT                     5004
#define ID_DISCONNECT                   5005
#define ID_INDICATOR_SOCK               5006
#define ID_LOG_OPEN                     5007
#define ID_MACRO_HIS1                   5008
#define ID_MACRO_HIS2                   5009
#define ID_MACRO_HIS3                   5010
#define ID_MACRO_HIS4                   5011
#define ID_MACRO_HIS5                   5012
#define ID_MACRO_PLAY                   5013
#define ID_MACRO_REC                    5014
#define ID_PANE_DELETE                  5015
#define ID_PANE_HSPLIT                  5016
#define ID_PANE_SAVE                    5017
#define ID_PANE_WSPLIT                  5018
#define ID_PROP_SET                     5019
#define ID_SETOPTION                    5020
#define ID_WINDOW_CLOSE                 5021
#define ID_FILE_ALL_SAVE                5022
#define ID_EDIT_NEW                     5023
#define ID_EDIT_UPDATE                  5024
#define ID_EDIT_DELETE                  5025
#define ID_EDIT_DUPS                    5026
#define ID_EDIT_CHECK                   5027
#define ID_CHARSCRIPT_END               5028
#define ID_SEND_BREAK                   5029
#define ID_MOUSE_EVENT                  5030
#define ID_CAPLIST_TERMCAP              5033
#define ID_CAPLIST_TERMINFO             5034
#define ID_EDIT_COPY_ALL                5035
#define ID_EDIT_PASTE_ALL               5037
#define IDM_GRAPDISP                    5039
#define IDM_SEARCH_REG                  5040
#define ID_SEARCH_NEXT                  5042
#define IDM_SEARCH_NEXT                 5043
#define ID_SERVERLIST_5044              5044
#define ID_SERV_PROTO                   5045
#define IDM_SERV_PROTO                  5046
#define ID_VIEW_SCROLLBAR               5048
#define ID_SE                           5049
#define ID_SEARCH_BACK                  5050
#define IDM_SEARCH_BACK                 5051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         5052
#define _APS_NEXT_CONTROL_VALUE         3061
#define _APS_NEXT_SYMED_VALUE           249
#endif
#endif
