//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RLogin.rc
//
#define IDR_MAINFRAME                   100
#define IDR_RLOGINTYPE                  101
#define IDR_SFTPMENU                    102
#define IDR_SFTPTOOL                    103
#define IDI_ACTIVE                      104
#define IDP_SOCKETS_INIT_FAILED         105
#define IDS_INDICATOR_STAT              106
#define IDB_BITMAP1                     107
#define IDB_BITMAP2                     108
#define IDB_BITMAP3                     109
#define IDB_BITMAP4                     110
#define IDB_BITMAP5                     111
#define IDB_BITMAP6                     112
#define IDB_BITMAP7                     113
#define IDD_ABOUTBOX                    114
#define IDD_ALGOPARADLG                 115
#define IDD_CHARSETPAGE                 116
#define IDD_CHMODDLG                    117
#define IDD_COLORPARADLG                118
#define IDD_EDITDLG                     119
#define IDD_FONTPARADLG                 120
#define IDD_ICONVDLG                    121
#define IDD_IDKEYDLG                    122
#define IDD_IDKEYFILEDLG                123
#define IDD_IDKEYPARADLG                124
#define IDD_KEYLISTPAGE                 125
#define IDD_KEYPARADLG                  126
#define IDD_PASSDLG                     127
#define IDD_PFDLISTDLG                  128
#define IDD_PFDPARADLG                  129
#define IDD_PROGDLG                     130
#define IDD_PROTOPAGE                   131
#define IDD_SERENTDLG                   132
#define IDD_SERVERLIST                  133
#define IDD_SFTPDLG                     134
#define IDD_SSHALGO                     135
#define IDD_TERMPAGE                    136
#define IDD_UPDATEDLG                   137
#define IDD_IDKEYSELDLG                 138
#define IDR_POPUPMENU                   140
#define IDD_ENTRYPAGE                   141
#define IDD_SERENTPAGE                  141
#define IDR_TEKWND                      141
#define IDD_CHATDLG                     146
#define IDD_DIALOG1                     147
#define IDD_CHATSTAT                    147
#define IDD_SCRIPTDLG                   148
#define IDD_PROXYDLG                    149
#define IDD_SCRNPAGE                    150
#define IDD_AUTORENDLG                  152
#define IDD_METADLG                     153
#define IDD_INFOCAPDLG                  154
#define IDD_ENVDLG                      155
#define IDD_ESCDLG                      156
#define IDD_ESCPARADLG                  157
#define IDD_CSIPARADLG                  158
#define IDM_KANJI_EUC                   200
#define IDM_KANJI_SJIS                  201
#define IDM_KANJI_ASCII                 202
#define IDM_KANJI_UTF8                  203
#define IDM_SFTP                        204
#define IDM_SFTP_ABORT                  205
#define IDM_SFTP_ALLDOWNLOAD            206
#define IDM_SFTP_ALLUPLOAD              207
#define IDM_SFTP_CHMOD                  208
#define IDM_SFTP_CLOSE                  209
#define IDM_SFTP_DELETE                 210
#define IDM_SFTP_DOWNLOAD               211
#define IDM_SFTP_MKDIR                  212
#define IDM_SFTP_REFLESH                213
#define IDM_SFTP_RENAME                 214
#define IDM_SFTP_UPLOAD                 215
#define IDM_XMODEM_UPLOAD               216
#define IDM_YMODEM_UPLOAD               217
#define IDM_ZMODEM_UPLOAD               218
#define IDM_XMODEM_DOWNLOAD             219
#define IDM_YMODEM_DOWNLOAD             220
#define IDM_ZMODEM_DOWNLOAD             221
#define ID_FILE_ALL_LOAD                240
#define IDC_DOINIT                      241
#define ID_EDIT_BOX                     243
#define ID_PAGE_PRIOR                   244
#define ID_PAGE_NEXT                    245
#define IDC_BACKFILE                    1000
#define IDC_BACKSEL                     1001
#define IDC_BANKGL1                     1002
#define IDC_BANKGL2                     1003
#define IDC_BANKGL3                     1004
#define IDC_BANKGL4                     1005
#define IDC_BANKGR1                     1006
#define IDC_BANKGR2                     1007
#define IDC_BANKGR3                     1008
#define IDC_BANKGR4                     1009
#define IDC_BOXBACK                     1010
#define IDC_BOXTEXT                     1011
#define IDC_BUTTON1                     1012
#define IDC_BUTTON2                     1013
#define IDC_BUTTON3                     1014
#define IDC_BUTTON5                     1015
#define IDC_REMOTE_UP                   1015
#define IDC_CHARBANK                    1016
#define IDC_CHARBANK1                   1017
#define IDC_CHARBANK2                   1018
#define IDC_CHARBANK3                   1019
#define IDC_CHARBANK4                   1020
#define IDC_CHARSET                     1021
#define IDC_CHARSET1                    1022
#define IDC_CHARSET2                    1023
#define IDC_CHARSET3                    1024
#define IDC_CHARSET4                    1025
#define IDC_CHMOD1                      1026
#define IDC_CHMOD2                      1027
#define IDC_CHMOD3                      1028
#define IDC_CHMOD4                      1029
#define IDC_CHMOD5                      1030
#define IDC_CHMOD6                      1031
#define IDC_CHMOD7                      1032
#define IDC_CHMOD8                      1033
#define IDC_CHMOD9                      1034
#define IDC_COLSET                      1035
#define IDC_COMCONFIG                   1036
#define IDC_CONNECTHOST                 1037
#define IDC_CONNECTPORT                 1038
#define IDC_DELAYMSEC                   1039
#define IDC_DELENTRY                    1040
#define IDC_DISPOFFSET                  1041
#define IDC_DISPZOOM                    1042
#define IDC_DSA2COPY                    1043
#define IDC_DISPZOOM2                   1043
#define IDC_DSA2MAKE                    1044
#define IDC_FONTQUALITY                 1044
#define IDC_DSA2PUB                     1045
#define IDC_EDIT1                       1046
#define IDC_EDITENTRY                   1047
#define IDC_EDIT3                       1047
#define IDC_ENDTIME                     1048
#define IDC_ENTRYNAME                   1049
#define IDC_FACENAME                    1050
#define IDC_FILENAME                    1051
#define IDC_FONTCODE                    1052
#define IDC_FILENAME2                   1052
#define IDC_FONTLIST                    1053
#define IDC_FONTLISTDEL                 1054
#define IDC_FONTLISTEDIT                1055
#define IDC_FONTLISTNEW                 1056
#define IDC_FONTSEL                     1057
#define IDC_HISMAX                      1058
#define IDC_ICONVSET                    1059
#define IDC_IDKEYFILE                   1060
#define IDC_IDKEYLOAD                   1061
#define IDC_IDKEYSAVE                   1062
#define IDC_IDKEYSEL                    1063
#define IDC_KANJICODE1                  1064
#define IDC_KANJICODE2                  1065
#define IDC_KANJICODE3                  1066
#define IDC_KANJICODE4                  1067
#define IDC_KEYASNDEL                   1068
#define IDC_KEYASNEDIT                  1069
#define IDC_KEYASNNEW                   1070
#define IDC_KEYCODE                     1071
#define IDC_KEYASNMETA                  1071
#define IDC_KEYFILENAME                 1072
#define IDC_KEYFILESELECT               1073
#define IDC_KEYLIST                     1074
#define IDC_KEYMAPS                     1075
#define IDC_KEYSTAT1                    1076
#define IDC_KEYSTAT2                    1077
#define IDC_KEYSTAT3                    1078
#define IDC_LISTENHOST                  1079
#define IDC_KEYSTAT4                    1079
#define IDC_LISTENPORT                  1080
#define IDC_LOADDEFAULT                 1081
#define IDC_LOCAL_CWD                   1082
#define IDC_LOCAL_LIST                  1083
#define IDC_LOGINNAME                   1084
#define IDC_MDI_TAB_CTRL                1085
#define IDC_MDI_TAB_CTRL_BAR            1086
#define IDC_NEWENTRY                    1087
#define IDC_OPTION                      1088
#define IDC_PASSNAME                    1089
#define IDC_PASSWORD                    1090
#define IDC_PASSNAME2                   1090
#define IDC_PFDDEL                      1091
#define IDC_PFDEDIT                     1092
#define IDC_PFDLIST                     1093
#define IDC_PFDNEW                      1094
#define IDC_PROGRESS1                   1095
#define IDC_PROMPT                      1096
#define IDC_RADIO1                      1097
#define IDC_RADIO2                      1098
#define IDC_RADIO3                      1099
#define IDC_RADIO4                      1100
#define IDC_RADIO5                      1101
#define IDC_REMOTE_CWD                  1102
#define IDC_REMOTE_LIST                 1103
#define IDC_RSA1COPY                    1104
#define IDC_RSA1MAKE                    1105
#define IDC_RSA1PUB                     1106
#define IDC_RSA2COPY                    1107
#define IDC_RSA2MAKE                    1108
#define IDC_RSA2PUB                     1109
#define IDC_SAVEDEFAULT                 1110
#define IDC_SCRNSIZE1                   1111
#define IDC_SCRNSIZE2                   1112
#define IDC_SCSZCOLS                    1113
#define IDC_SCSZFONT                    1114
#define IDC_SERVERLIST                  1115
#define IDC_SCSZCOLS2                   1115
#define IDC_SERVERNAME                  1116
#define IDC_SHIFT                       1117
#define IDC_SIZEPROG                    1118
#define IDC_SOCKNO                      1119
#define IDC_SSHALGO                     1120
#define IDC_SSHIDKEY                    1121
#define IDC_SSHPFD                      1122
#define IDC_TERMNAME                    1123
#define IDC_TIMELIMIT                   1124
#define IDC_TITLE                       1125
#define IDC_TOTALSIZE                   1126
#define IDC_TRANSPARENT                 1127
#define IDC_TRANSRATE                   1128
#define IDC_USERNAME                    1129
#define IDC_WHEELSIZE                   1130
#define IDC_USERNAME2                   1130
#define IDC_HOSTADDR                    1130
#define IDC_VISUALBELL                  1131
#define IDC_VISUALBELL2                 1132
#define IDC_RECVCRLF                    1132
#define IDC_MOUSE_BTN1                  1133
#define IDC_HISFILE_SEL                 1134
#define IDC_HISFILE_SEL2                1135
#define IDC_AUTOLOG_SEL                 1135
#define IDC_MOUSE_BTN2                  1135
#define IDC_COMBO1                      1136
#define IDC_IDKEY_TYPE                  1136
#define IDC_ECHOCRLF                    1136
#define IDC_SENDCRLF                    1136
#define IDC_COMBO2                      1137
#define IDC_IDKEY_BITS                  1137
#define IDC_MOUSE_KEY1                  1137
#define IDC_LIST2                       1138
#define IDC_IDKEY_LIST                  1138
#define IDC_MOUSE_KEY2                  1138
#define IDC_ESCEDIT                     1138
#define IDC_BUTTON4                     1139
#define IDC_IDKEY_UP                    1139
#define IDC_BUTTON6                     1140
#define IDC_IDKEY_DOWN                  1140
#define IDC_IDKEY_DEL                   1141
#define IDC_IDKEY_INPORT                1142
#define IDC_IDKEY_EXPORT                1143
#define IDC_IDKEY_NAME                  1144
#define IDC_IDKEY_CREATE                1145
#define IDC_IDKEY_COPY                  1146
#define IDC_NAME                        1146
#define IDC_IDKEY_PROG                  1147
#define IDC_MESSAGE                     1148
#define IDC_LOCAL_UP                    1149
#define IDC_KEEPALIVE                   1153
#define IDC_CHECK1                      1157
#define IDC_CHECK2                      1158
#define IDC_SLEEPSEC                    1158
#define IDC_NODETREE                    1159
#define IDC_SENDSTR                     1160
#define IDC_RECVSTR                     1161
#define IDC_NEWNODE                     1162
#define IDC_UPDATENODE                  1163
#define IDC_DELNODE                     1164
#define IDC_NEXTNODE                    1165
#define IDC_CHATEDIT                    1165
#define IDC_MAKECHAT                    1166
#define IDC_CHATEDIT2                   1166
#define IDC_PROXYSET                    1166
#define IDC_TIMEPROG                    1167
#define IDC_STATUS                      1168
#define IDC_EDIT2                       1170
#define IDC_TEXT                        1170
#define IDC_NAMEOK                      1174
#define IDC_ALL_SET                     1175
#define IDC_ALL_CLR                     1176
#define IDC_TEXTCOL                     1177
#define IDC_BACKCOL                     1178
#define IDC_FONTNUM                     1178
#define IDC_LIST1                       1179
#define IDC_INFOLIST                    1179
#define IDC_ENV_LIST                    1179
#define IDC_ESCLIST                     1179
#define IDC_LOADCAP                     1180
#define IDC_CSILIST                     1180
#define IDC_ENTRY                       1181
#define IDC_LOADINFO                    1182
#define IDC_TERMCAP                     1182
#define IDC_INFOCAP                     1183
#define IDC_SSL_RADIO1                  1184
#define IDC_SSL_RADIO2                  1185
#define IDC_CODE                        1185
#define IDC_SSL_RADIO3                  1186
#define IDC_CODEEXT2                    1186
#define IDC_CEXT2                       1186
#define IDC_SSL_RADIO4                  1187
#define IDC_CEXT1                       1188
#define IDC_ATTR1                       1201
#define IDC_ATTR2                       1202
#define IDC_ATTR3                       1203
#define IDC_ATTR4                       1204
#define IDC_ATTR5                       1205
#define IDC_ATTR6                       1206
#define IDC_ATTR7                       1207
#define IDC_ATTR8                       1208
#define IDB_ATTR1                       1221
#define IDB_ATTR2                       1222
#define IDB_ATTR3                       1223
#define IDB_ATTR4                       1224
#define IDB_ATTR5                       1225
#define IDB_ATTR6                       1226
#define IDB_ATTR7                       1227
#define IDB_ATTR8                       1228
#define IDM_RESET_TAB                   1800
#define IDM_RESET_BANK                  1801
#define IDM_RESET_ATTR                  1802
#define IDM_RESET_TEK                   1803
#define IDM_RESET_ESC                   1804
#define IDM_RESET_MOUSE                 1805
#define IDM_RESET_ALL                   1806
#define IDC_ALGO_LIST1                  2001
#define IDC_ALGO_LIST2                  2002
#define IDC_ALGO_LIST3                  2003
#define IDC_ALGO_LIST4                  2004
#define IDC_ALGO_LIST5                  2005
#define IDC_ALGO_LIST6                  2006
#define IDC_ALGO_LIST7                  2007
#define IDC_ALGO_LIST8                  2008
#define IDC_ALGO_LIST9                  2009
#define IDC_BOX0                        2100
#define IDC_BOX1                        2101
#define IDC_BOX2                        2102
#define IDC_BOX3                        2103
#define IDC_BOX4                        2104
#define IDC_BOX5                        2105
#define IDC_BOX6                        2106
#define IDC_BOX7                        2107
#define IDC_BOX8                        2108
#define IDC_BOX9                        2109
#define IDC_BOX10                       2110
#define IDC_BOX11                       2111
#define IDC_BOX12                       2112
#define IDC_BOX13                       2113
#define IDC_BOX14                       2114
#define IDC_BOX15                       2115
#define IDC_PROTO1                      2201
#define IDC_PROTO2                      2202
#define IDC_PROTO3                      2203
#define IDC_PROTO4                      2204
#define IDC_PROTO5                      2205
#define IDC_PROTO6                      2206
#define IDC_PROTOCHECK1                 2301
#define IDC_PROTOCHECK2                 2302
#define IDC_PROTOCHECK3                 2303
#define IDC_PROTOCHECK4                 2304
#define IDC_PROTOCHECK5                 2305
#define IDC_PROTOCHECK6                 2306
#define IDC_PROTOCHECK7                 2307
#define IDC_PROTOCHECK8                 2308
#define IDC_PROTOCHECK9                 2309
#define IDC_PROTOCHECK10                2310
#define IDC_PROTOCHECK11                2311
#define IDC_PROTOCHECK12                2312
#define IDC_STATUS1                     2401
#define IDC_STATUS2                     2402
#define IDC_STATUS3                     2403
#define IDC_STATUS4                     2404
#define IDC_TERMCHECK1                  2501
#define IDC_TERMCHECK2                  2502
#define IDC_TERMCHECK3                  2503
#define IDC_TERMCHECK4                  2504
#define IDC_TERMCHECK5                  2505
#define IDC_TERMCHECK6                  2506
#define IDC_TERMCHECK7                  2507
#define IDC_TERMCHECK8                  2508
#define IDC_TERMCHECK9                  2509
#define IDC_METAKEY1                    8001
#define IDC_METAKEY2                    8002
#define IDC_METAKEY3                    8003
#define IDC_METAKEY4                    8004
#define IDC_METAKEY5                    8005
#define IDC_METAKEY6                    8006
#define IDC_METAKEY7                    8007
#define IDC_METAKEY8                    8008
#define IDC_METAKEY9                    8009
#define IDC_METAKEY10                   8010
#define IDC_METAKEY11                   8011
#define IDC_METAKEY12                   8012
#define IDC_METAKEY13                   8013
#define IDC_METAKEY14                   8014
#define IDC_METAKEY15                   8015
#define IDC_METAKEY16                   8016
#define IDC_METAKEY17                   8017
#define IDC_METAKEY18                   8018
#define IDC_METAKEY19                   8019
#define IDC_METAKEY20                   8020
#define IDC_METAKEY21                   8021
#define IDC_METAKEY22                   8022
#define IDC_METAKEY23                   8023
#define IDC_METAKEY24                   8024
#define IDC_METAKEY25                   8025
#define IDC_METAKEY26                   8026
#define IDC_METAKEY27                   8027
#define IDC_METAKEY28                   8028
#define IDC_METAKEY29                   8029
#define IDC_METAKEY30                   8030
#define IDC_METAKEY31                   8031
#define IDC_METAKEY32                   8032
#define IDC_METAKEY33                   8033
#define IDC_METAKEY34                   8034
#define IDC_METAKEY35                   8035
#define IDC_METAKEY36                   8036
#define IDC_METAKEY37                   8037
#define IDC_METAKEY38                   8038
#define IDC_METAKEY39                   8039
#define IDC_METAKEY40                   8040
#define IDC_METAKEY41                   8041
#define IDC_METAKEY42                   8042
#define IDC_METAKEY43                   8043
#define IDC_METAKEY44                   8044
#define IDC_METAKEY45                   8045
#define IDC_METAKEY46                   8046
#define IDC_METAKEY47                   8047
#define IDC_METAKEY48                   8048
#define IDC_METAKEY49                   8049
#define IDC_METAKEY50                   8050
#define IDC_METAKEY51                   8051
#define IDC_METAKEY52                   8052
#define ID_APP_QUIT                     32768
#define ID_DISCONNECT                   32769
#define ID_INDICATOR_SOCK               32770
#define ID_LOG_OPEN                     32771
#define ID_MACRO_HIS1                   32772
#define ID_MACRO_HIS2                   32773
#define ID_MACRO_HIS3                   32774
#define ID_MACRO_HIS4                   32775
#define ID_MACRO_HIS5                   32776
#define ID_MACRO_PLAY                   32777
#define ID_MACRO_REC                    32778
#define ID_PANE_DELETE                  32779
#define ID_PANE_HSPLIT                  32780
#define ID_PANE_SAVE                    32781
#define ID_PANE_WSPLIT                  32782
#define ID_PROP_SET                     32783
#define ID_SETOPTION                    32784
#define ID_WINDOW_CLOSE                 32785
#define ID_FILE_ALL_SAVE                32786
#define ID_EDIT_NEW                     32787
#define ID_EDIT_UPDATE                  32789
#define ID_EDIT_DELETE                  32790
#define ID_EDIT_DUPS                    32792
#define ID_EDIT_CHECK                   32794
#define IDM_CHATSTOP                    32795
#define ID_CHARSCRIPT_END               32795
#define ID_SEND_BREAK                   32796
#define ID_MOUSE_EVENT                  32799
#define IDM_TEKDISP                     32801
#define IDM_TEK_CLOSE                   32802
#define IDM_TEK_SAVE                    32803
#define IDM_TEK_CLEAR                   32805
#define IDM_TEK_MODE                    32807
#define IDM_CAP_INPORT                  32808
#define IDM_CAP_EXPORT                  32809
#define ID_CAPLIST_32810                32810
#define ID_CAPL_CLIP                    32811
#define IDM_CAPL_CLIP                   32812
#define IDM_CAPL_CLIPBORD               32813
#define IDM_CAP_CLIPBORD                32814
#define ID_CAPLIST_TERMCAP              32815
#define ID_CAPLIST_TERMINFO             32816
#define IDM_INFO_INPORT                 32817
#define IDM_INFO_EXPORT                 32818
#define IDM_INFO_CLIPBORD               32819
#define IDM_BROADCAST                   32833
#define ID_EDIT_COPY_ALL                32836
#define ID_EDIT_P                       32838
#define ID_EDIT_PASTE_ALL               32839

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           246
#endif
#endif
